# This file is for render site varibles and plugins
# don't remove this file.
# The presence of this file is for compatibility with Blogdown and Forestry.
#
# The actual configuration files are stored in the `config/_default/` folder.


######################### site variables ##############################
# customize your color and font from here.
[params.variables]
color_primary = "#1e52f0"
color_secondary = "#001111"
body_color = "#fff"
text_color = "#777e90"
text_dark = "#2e445c"
text_light = "#959595"
border_color = "#ACB9C4"
black = "#000"
white = "#fff"
dark = "#222"
light = "#eee"

# font variables
# base font size for full website, 
font_size = "17px" # default is 16px

# Font Scale Sizes
# "minorSecond": 1.067,
# "majorSecond": 1.125,
# "minorThird": 1.2,
# "majorThird": 1.25,
# "perfectFourth": 1.333,
# "augmentedFourth": 1.414,
# "perfectFifth": 1.5,
# "goldenRatio": 1.618
font_scale = "1.25" # default is "majorThird": 1.25

# go to https://fonts.google.com/ to find the font you want to use. select your font and copy only the bold part from the URL. and paste it here.
# example: "Work+Sans:wght@400;500;600"
font_primary = "Space+Grotesk:wght@400;500;600"
font_primary_type = "sans-serif"            # [serif/sans-serif]
font_secondary = ""
font_secondary_type = ""                    # [serif/sans-serif]


############################# Plugins ##############################

# CSS Plugins
# [[params.plugins.css]]
# link = "plugins/swiper/swiper-bundle.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/webfont/webfont-loader-2.js"